### ISSUE TITLE
Neos backend crashes with "TypeError: _ is not a function"

### ISSUE THREAD

**Issue by simonschaufi** [Flowpack/neos-matomo#42]
UI version: v7.3.3
Neos Matomo 3.4.0

When I click in the inspector on the "Stats" icon, then the whole neos backend crashes with the error: 

```
react-dom.production.min.js:209 TypeError: _ is not a function
    at Function.ye.ticks (time.js:49:12)
    at TimeSeriesView.j.getXTicks (index.js:114:29)
    at TimeSeriesView.render (index.js:139:29)
    at gi (react-dom.production.min.js:182:192)
    at fi (react-dom.production.min.js:181:224)
    at So (react-dom.production.min.js:263:490)
    at Qj (react-dom.production.min.js:246:265)
    at Kj (react-dom.production.min.js:246:194)
    at yj (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
time.js:49 Uncaught (in promise) TypeError: _ is not a function
    at Function.ye.ticks (time.js:49:12)
    at TimeSeriesView.j.getXTicks (index.js:114:29)
    at TimeSeriesView.render (index.js:139:29)
    at gi (react-dom.production.min.js:182:192)
    at fi (react-dom.production.min.js:181:224)
    at So (react-dom.production.min.js:263:490)
    at Qj (react-dom.production.min.js:246:265)
    at Kj (react-dom.production.min.js:246:194)
    at yj (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
```

Is this an error in the neos matomo package or in the neos core?

**Comment by simonschaufi** [comment]
I'll close this again as this bug is not related to the backage but to neos core.
